### ISSUE TITLE
removePlayerWhenBanned malfunction?

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#1002]
"removePlayerWhenBanned": true,

Hi there.
It seems that when I use this function, and one of my moderators bans someone (Using Ban Hammer Plugin), the player is not expelled from his/her faction.

However, I have seen this work in some occasions, but I'm not sure what command was executed. (Maybe the vanilla /kick or /ban, or maybe this was because the ban was permanent).

------------------------------
Factions & Mcore versions: 2.8.2
Server version: Spigot for mc 1.8.8

**Comment by ulumulu1510** [comment]
Hello MithrandirCraft,

This function will depend on your ban plugins implementation:
https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/engine/EngineMain.java#L1045

We are asking the BukkitAPI whether a Player is banned in this case, so if Ban Hammer doesn't tell Bukkit/Spigot that the player is banned, we will not remove the players faction data.

I am not sure how Ban hammer works, but it could be that they only tell Bukkit that a player is banned when you use it's PermaBan feature (which is what I would expect of it atleast). In case you wish this to be handled differently, you would have to ask the Ban Hammer authors to change that specific feature of theirs.

Because all we can do in this regards, is to ask bukkit whether a player is banned.

**Comment by MithrandirCraft** [comment]
Thanks for the hint! :)
