### ISSUE TITLE
Factions "instance.json" not saving upon restart

### ISSUE THREAD

**Issue by nzzane** [MassiveCraft/Factions#1008]
Hey, so like the title says. 
I will edit the config to change 'worldsnoclaiming' to only allow the world "Factions" so i disable all other worlds.  When the server restarts the "instance.json" is fresh and my changes are not saved.  
Anyone know why it is doing this?

Factions: 2.2.2
Tekkit 1.6.4
MCPC+

**Comment by ulumulu1510** [comment]
You are makig a ticket for a far outdated version of factions. By default, we do not offer support for outdated versions since the issue present here is most likely, if not surely, fixed already.

Try to run your edited file through an online json checker and see if it validates it as correct Json. If this is the not case, try making correct json. If it is correct already, only updating could help. (I know it's unlikely for you to update since you run a modpack, but if you stick with the old Version  you stick with the old bugs )
