### ISSUE TITLE
Factions permissions config

### ISSUE THREAD

**Issue by darkarrow** [MassiveCraft/Factions#1064]
Question as posted on the spigotmc forums:

"I'm currently using factions 2.8.7Beta

So what I am trying to do is force the container permission to be yes for relation enemy factions but letting the faction leader change any of the other container relation permissions he wants.

I know how to make it so enemies can open containers and make it so the leader can't change any of the other relations along with the enemy one however I'd like them to be able to change the stuff to their liking.

I'm not sure if this is possible with just the vanilla factions plugin or if maybe an addon plugin can be made to do it or already exists. The reason I want it to be this way is so that leaders/officers can make private faction land that certain members can't do stuff with, including opening chests, but doesn't interfere with enemy factions trying to raid. Also allowing them to change the permissions for other relations as they choose.

Thanks!"

I'm not sure if this would be a feature request or if it's just something that maybe you could help me setup. I noticed in the mperm folder the files contain a priority number so I thought maybe if I made a new json file with a lower priority and the contents of container but making it not editable and only for ENEMY relation it would work but factions seemed to just ignore the file entirely. Any help is appreciated! Thanks

**Comment by MarkehMe** [comment]
I think I understand the issue :laughing: I think the command you're looking for is ```/f perm``` - you can find more information in the documentation:

* https://www.massivecraft.com/factions#commands
* https://www.massivecraft.com/factions-configure

(Apologies for the delayed response. We've all been quite busy lately)

**Comment by darkarrow** [comment]
That's fine I understand people get busy, though not quite the issue.

I know about the /f perm command but what I'm trying to do is make it so one relation is locked while the other relations for the same perm are able to be changed by the leader of the faction.

Example: container permissions for relation enemy are locked to true while the other relations of it are able to be changed by regular users.

**Comment by ulumulu1510** [comment]
We do not have a "priority" system in place as yoh imagine. Priority is for display order, not file management. The important thing about those files is their name, as they get identified through it.

What you want to achieve is not possible with plain factions and its configurations.

You would have to make a seperate plugin that does this for you. I personally don't see the benefit of your suggestion to gameplay, because if enemies are allowed to take it...what stops you faction members who want to loot you from enemying you in your base and loot all you stuff? So I think it makes only sense on your very server.
