### ISSUE TITLE
attack a member

### ISSUE THREAD

**Issue by FredericFernandes** [MassiveCraft/Factions#1100]
Sorry but I tried to the best of English spoken (Google translate) 

Good evening to you ! Since 2 days I try and I try everything on google to find solution to my problem but I can not find anything ... I 'm desperate seriously ...
 
Let me explain I have my spawn is claim as ' SafeZone ' but when I attack another player durability decreases, while I'm at spawn and of course another issue , members of the same faction can was attacked them o_O what is really practical : D .
 
 
I use Cauldron 1.7.10 , Faction and are Massivecore same version. *
 
I hope to find solution here because this problem bothers me greatly !
 
 
Thank you.

**Comment by ulumulu1510** [comment]
We do not support Cauldron, as it is severely outdated. I can't give you any good advice, since using software that outdated is a huge security issue and even our software had more bugs in those times.

Reverting back to a former version of massivecore and factions might work in your case, but we offer no support for outdated versions of our software. I hope this has cleared your issue.
