### ISSUE TITLE
Players of same faction can attack each other

### ISSUE THREAD

**Issue by Bobobaal** [MassiveCraft/Factions#1116]
First of all
Factions version: 2.8.19
Massivecore version: 2.8.19

Problem:

So there are 3 players:
Player A, B and C.
A and B are in the same faction because they're good friend and know each other. During pvp they both fight player C. During the attack they hurt each other without knowing. A kills B and C kills B.
So this means player A and B could hit each other even if they're from the same faction and friendlyfire is off.

^^^^^^^^^ That's an example

Short: Players can hurt their own faction members when friendlyfire is off whilst friendlyfire should prevent hitting own faction members.

**Comment by ulumulu1510** [comment]
As stated in the documentation, factions is land based. If these two (A & B) are on land from faction X where friendlyfire is enabled, they can hurt each other.

Example:
1) A & B are in their faction land. Their faction has fiendlyfire off. Now a raider, person C, comes along. A can hit B as much as he wants here and nothing will happen.
2) A&B are in the warzone where friendlyfire is on. If the now fight person C and mistakenly hit each other, it will hurt since the land they are fighting on allows friendlyfire.

So as you can see, this is an intended feature of Factions.
