### ISSUE TITLE
Modifying and re-uploading

### ISSUE THREAD

**Issue by Redstone-Pro-73** [MassiveCraft/Factions#1121]
Hello, I made my own modified version of MassiveCore and Factions (both by MassiveCraft). I was wondering if I am allowed to upload them on Spigot as a premium resource. My modified version currently changes (almost) every message to a new (in my opinion) way better and cleaner version. I would probably put it on spigotmc.org for only $0.99 or $1.99. I am planning on actually adding features (not just cosmetic changes) in the future. Before I post it I'd like for you permission. Thank you :D

**Comment by MarkehMe** [comment]
This is a really bad idea in my opinion. There are four issues I see with this:

1. You will be in charge of future upgrades for that build of Factions and MassiveCore, you would have to take full responsibility to upgrade the plugin in the future.. and any issues reported with your plugin will have to be considered an issue with your plugin - not the original Factions and MassiveCore (again, your responsibility) 
2. Your MassiveCore could (and _probably_ will) become incompatible with other MassiveCore plugins in the future. This will most likely annoy your server operators. You also can't run two versions of a plugin. 
3. This is kind of morally wrong - MassiveCraft developers and volunteers have put years of time and effort into making these plugins, you are simply changing some words and adding minor features.. and then selling it? 
4. Please [see here](https://github.com/MassiveCraft/Factions/tree/master/licenses) for the licenses - everything you do must be in accordance to these. I believe factions is under GPL<sup>_^#_</sup> - this comes with restrictions. 

If you want to add features consider creating a seperate plugin that uses [the Factions API](https://www.massivecraft.com/factions-develop) or an [alternative API](https://github.com/MarkehMe/FactionsFramework).

----

<sup>_^_</sup> _https://opensource.org/licenses/GPL-3.0_
 <sup>_#_</sup> _http://choosealicense.com/licenses/gpl-3.0/_

**Comment by Redstone-Pro-73** [comment]
Okay. I'll just release it for free. Is that still okay? And I'll try my
best to continue compatibility with all MassiveCraft plugins. I'll also
update it frequently. Thank you :D

**Comment by MarkehMe** [comment]
I still do think you should consider just creating external plugins (you could sell these).

**Comment by ulumulu1510** [comment]
@Cayorion

I tagged the owner of MassiveCraft and thus holder of the intellectual Property of the two plugins you linked.

In my opinion as a contributor, releasing a modified version of MassiveCore and Factions is a bad idea.
Not only will people come to you with problems that lie in our version of MassiveCore,  but also some of your customers/users will come to us. It would create a havoc over responsibility and I am quite sure you underestimate that.

Also,  if I am thinking myself in your position right now, do you know how much work it will be to stay up to date with our changes? How many times you will have to fetch the changes in git an panestackingly amend them into "your" version of it? I know what I am talking about,  because that is what we contributors do every time we work on it. But I am not sure you are aware that this will be demanded by any potentail future users of your version, as they would surely want it to be compatible with all of our other plugins.

I second the morality and license points Markehme brought up.

If you want to do something for the community,  why not make a PR where you/they are able to change things such as these messages and colors? Wouldn't that benefit the community more?

**Comment by Redstone-Pro-73** [comment]
Okay. Thank you all for your responses. I might actually consider creating
that pull request :D Thank you all for your time and have now reconsidered
my discision. I won't make my custom version public. Thank you again for
all of your (quick) responses.

**Comment by Redstone-Pro-73** [comment]
Also, I don't think the API has enough functionality to actually add the features I think people would want. Yet again I'd have to go check the API. I'm currently away from my PC and am only on my phone at the moment. I'll check it some time within two days.

**Comment by MarkehMe** [comment]
There is always room for improvement with the API too - please let us know what you're after! 😁

**Comment by Redstone-Pro-73** [comment]
If you want more information about my custom build is, and my ideas on how
I can implement it via a pull request, is there some type of PM we can talk
through? You can even come on my network too see my current custom build.
Which maybe I can turn into an external plugin or even get it in a pull
request.

**Comment by MarkehMe** [comment]
I'm really curious! 😄 

Can you add me on skype - markehme - and we can have a chat about your ideas?

**Comment by Redstone-Pro-73** [comment]
Sure. I can't just yet. It's the forth today and will be away from my PC,
but surely tomorrow! 😀

**Comment by Redstone-Pro-73** [comment]
Do you have discord? I don't have skype, sorry. You can add me on discord with this email: redstonepro73@gmail.com
Maybe I can

**Comment by Redstone-Pro-73** [comment]
Whoops... didn't mean to close the issue :I I just got skype and will add you. If you do please still add me on discord since that is where I will respond the fastest.
