### ISSUE TITLE
Ask: how to allow player mine spawner on other factions (enemy's faction)

### ISSUE THREAD

**Issue by tuanjr** [MassiveCraft/Factions#1135]
as title said: how to allow player mine spawner on other factions (enemy's faction)?
Thank you :)

**Comment by oloflarsson** [comment]
https://www.massivecraft.com/factions-configure

You can configure it so territories are not protected at all. For specific blocks only this is not possible. It's either full block break access for all blocks or no block breaking at all. There is also the painbuild permission. That would allow limited editing because you take damage when you edit.
