### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by Phiwa** [MassiveCraft/Factions#484]
Is there any chance to get a maven-repo to use for dependencies?
I couldn't find one and just wondered if there actually isn't a repo or I simply missed it. :)

**Comment by zachoooo** [comment]
Hello, this really needs a maven to make development compatible with maven. Adding local repos or system scope dependencies is horrible practice.

**Comment by NathanWolf** [comment]
I'd still like to see this too, for what it's worth :)

I actually use reflection to access the Factions API .. which is probably even more horrible practice, but keeps my project "1 click buildable".

**Comment by ulumulu1510** [comment]
@NathanWolf 
I hope you are aware of this page: http://www.massivecraft.com/factions-develop
In my eyes, every data that you need to get out of factions can be accessed with the fundation this page provides.

**Comment by NathanWolf** [comment]
I am aware of the page, though since you've brought it up that page didn't cover *any* of my use-cases. It'd be nice to see some simple (and I'm thinking very common) examples such as canPlayerBuildAt, or an example of how to check if a player is allowed to PVP (I still haven't figured this one out).

That said, if you'll note I've said I am using reflection not because there is no API, but because there is no Maven repository. This is the only way I can avoid having to distribute Factions with my own code.

**Comment by ulumulu1510** [comment]
@NathanWolf
If you want to help us,  the developement team, please make a list of user cases you would have liked to see in the documentation and send it over to me in skype:
Id: titanusbenjaminus 

About the maven repository:
Currently only one of our dev team is realy working with maven and cayorion has removed maven support on massivecore because of (debatable) reasons. I am not too positive that we will offer Maven support too soon, but note that I am the lowest ranked in our team and making the decitions.

**Comment by Pocketkid2** [comment]
Please make a maven repo!

**Comment by Phiwa** [comment]
That would really make life easier for us. :)

**Comment by timbru31** [comment]
Voting for this issue. An official maven repo would make my life much easier.

**Comment by MarkehMe** [comment]
I posted a simple alternative here: https://github.com/MassiveCraft/Factions/issues/922

**Comment by timbru31** [comment]
I host my own artifactory server, but an official repo would be better though. :)

**Comment by NoChanceSD** [comment]
Maven would still be simpler than that and easier to track which version we are depending on. Is "Because I like having my plugins downloaded at BukkitDev" really the motive for not adding maven? 
That makes absolutely no sense, just say you have no idea how maven works.

**Comment by zachoooo** [comment]
Hello,

Please reopen this ticket. This needs to be done.

**Comment by Rocologo** [comment]
I would love to have a maven repository too.

**Comment by zachoooo** [comment]
@Rocologo I'm surprised this still hasn't occurred.

**Comment by EncryptedData** [comment]
Why hasn't this been done yet? This would help me and my dev team so much.

**Comment by zachoooo** [comment]
If not maven, what about gradle? Both maven and gradle would be preferred.

**Comment by timbru31** [comment]
Feel free to use my maven repo, I'll try to keep the version up to date: https://repo.dustplanet.de/artifactory/ext-release-local/

**Comment by EncryptedData** [comment]
Thanks @timbru31

**Comment by Minikloon** [comment]
As this is open source there's also https://jitpack.io.

**Comment by RoboMWM** [comment]
@Minikloon Jitpack won't work here, at least not for any recent versions as the pom seems to be pointing to inaccessible directories. https://jitpack.io/com/github/MassiveCraft/Factions/a9adc388e8/build.log
