### ISSUE TITLE
Use Maven?

### ISSUE THREAD

**Issue by jengel3** [MassiveCraft/Factions#607]
Like seriously, I'd like to contribute to Factions & Mcore, but setting up the build paths is so annoying. It would be awesome if Maven was used to manage dependencies instead.

**Comment by gdude2002** [comment]
Well, this was interesting.

There's a fair few plugins that support Factions out there, but I'm not sure how they're actually built - I don't see how Maven could be forced to build without the Factions jar in some Maven repo, but I guess you could have Gradle manually download it or something.. From what the dev has said here and on #484 I feel like that's what he wants, since it'd artificially boost his download stats on Bukkitdev.

The thing is, though, Factions changes drastically between versions, so supporting it as it goes forward is pretty tough already. It almost looks like this is intentional!

I came here hoping there was a Maven repo somewhere as I'm looking to support Factions in my own plugin as well, but I guess I'm out of luck.

**Comment by vemacs** [comment]
@gdude2002 You can set up a local maven repo, [install it manually](http://lmgtfy.com/?q=3rd+party+jar+maven), or use a <systemPath> dependency like in https://github.com/games647/ScoreboardStats/blob/master/pom.xml#L227

**Comment by gdude2002** [comment]
I'm not actually using Maven (I'm using Gradle), but I more object to how money-motivated the project is than not having an easy way to do this. I totally understand getting paid for work, but I just feel like making life hard for the community that essentially gives you money isn't a good way to do things.

**Comment by Pocketkid2** [comment]
Please make a maven repo!

**Comment by Miclebrick** [comment]
lol...
