### ISSUE TITLE
/F claim issue

### ISSUE THREAD

**Issue by TheDarkMC** [MassiveCraft/Factions#762]
When ever i try to claim land with the factions plugin it will say Error the "commandsender" has been servered this shouldnt happen and i am the CoOwner of my server and also you cant set a Fhome 
i have used this plugin before the update and wish to use it more can you please fix it.

**Comment by oloflarsson** [comment]
Are you running a Cauldron server?

**Comment by TheDarkMC** [comment]
Yes we are

**Comment by HT1972** [comment]
I am also asking for the same help as thedarkmc is since we are owners of a server, After deleting the mcstore file, the faction stuff worked for about a min then when back to the same thing problem with /f claim  error Your "commandSender link" we cant claim any land at all, we are a new server and would like to get this fix before we get alot of ppl on can you please help on this matter.

**Comment by stevoace** [comment]
Yep, also in the same boat

**Comment by magnusulf** [comment]
We do not support Cauldron.
