### ISSUE TITLE
UUID in Faction

### ISSUE THREAD

**Issue by farget92** [MassiveCraft/Factions#779]
Hello community,
I have really weird problem, with faction.
In fact in command /f f [faction] or [nick], because that command is working well.
But nick of players isn't displaying correctly.

http://prntscr.com/5t9ros

In log is not any error. Or I can not find anything.

**Comment by ulumulu1510** [comment]
You have to give us way more information about your server first. Which Core-OS, MassiveCore and Factions version are you using?

Please issue the command again and look in the console for the time the command was run. There may or may not be an error, just please do proper checking again.

**Comment by farget92** [comment]
Well,
a server run on Linux server - Debian, with Java runtime 1.7.0_60 .
Version of faction is 2.7.5.

Problem is still here.
This problem appear when the server was force to close.
We have also problems with Jobs and McMMO, perhaps it is connected together.

**Comment by drtshock** [comment]
Increase your user cache in the spigot.yml

**Comment by ulumulu1510** [comment]
This issue seems to be resolved.

**Comment by aeonlamb** [comment]
Hello, I am having this issue on factions version 2.13.1, spigot 1.12.2, Java 8 ... 

The issue only seems to occur after the server crashes/goes down unexpectedly. After that, the names are gone from /f f, only UUIDs appear. If a player logs in after all of the names are decoupled from UUIDs, the name will be saved once again, until the server crashes again and this issue comes up. What is odd is, it does not happen every single time the server crashes- I can't tell what circumstances specifically cause it. This has been happening on my server for a long time (since 1.9 I believe), the thing is, it happens rather infrequently due to it being connected to crashes.

**Comment by aeonlamb** [comment]
I've tried increasing my user cache in spigot.yml and it has not fixed this issue. [Screenshot here](https://i.imgur.com/Lg9PVe2.png) to illustrate my problem... (this happens to every single faction on the server after a crash). Can someone please re-open this? @drtshock @ulumulu1510
