### ISSUE TITLE
Factions powerOfflineLossPerDay

### ISSUE THREAD

**Issue by Apotheosis1337** [MassiveCraft/Factions#795]
Factions version : 2.7.5
MCore Version : 2.7.5

/f config powerOfflineLossPerDay -1.0 doestn seem to do the trick..
As well I cannot find powerOfflineLossPerDay in the config as well, which is weird.. There was such option before?

**Comment by Apotheosis1337** [comment]
The update this was included in was 1.5.0 in 2011 ._.

**Comment by magnusulf** [comment]
Maybe that feature is removed.

**Comment by Apotheosis1337** [comment]
Any plans to add it back ?

**Comment by magnusulf** [comment]
@oloflarsson

**Comment by oloflarsson** [comment]
If you want to work on adding this feature back you are welcome to @magnusulf. But there are some odds and ends to that we should discuss on TeamSpeak first in such case.

I'd say there are no immediate plans on adding back support for this, but it would be possible with a bit of work.

**Comment by Apotheosis1337** [comment]
Thanks for your time guys,

Hopefully will be readded. Would be a great feature

**Comment by Apotheosis1337** [comment]
Is this going to be readded soon? =S

**Comment by magnusulf** [comment]
This feature is not going to be added soon. If someone really wants this feature they could make a PR for it.

**Comment by monsquazz** [comment]
Really wish this feature was readded. I've seen some players exploiting this by joining factions, maxing out their power and leaving the server. Of course they log once in a while to not to be automatically kicked from faction due to inactivity. It is especially problematic when economy add-on isn't used and factions don't need to pay upkeep for their claims.

I am not sure if I understand this correctly, but I think it can be easily implemented modifying task/TaskPlayerPowerUpdate.java so in addition to boosting online players' power, it could decrease offline players power.

**Comment by magnusulf** [comment]
Duplicate of #368
