### ISSUE TITLE
Silly ask... Translate ?

### ISSUE THREAD

**Issue by Technowix** [MassiveCraft/Factions#805]
Again, i'm here to re up the endless "can you give way to translate the plugins ? Change built'in message ?" from a config file :)

**Comment by magnusulf** [comment]
That task is simp,y so difficult it won't happen. First of all some messages are generated from a few a parameters, so those messages would be difficult to implement a config for (not impossible and the config would be confusing. Second of all, adding all messages to a config would take quite some time. In the end this would also slow down future development speed, because all messages has to be accessed through a config and not just typed in. Not to mention the likelihood of forgetting to add a message to the config.
