### ISSUE TITLE
Op's Talk Twice?

### ISSUE THREAD

**Issue by vasperal** [MassiveCraft/Factions#816]
http://prntscr.com/68k78a My problem  any fix? Also how do i set warzone and safezone thanks!

**Comment by ulumulu1510** [comment]
Although I don't believe this issue is caused by factions, you will need to provide much more info:

What bukkit/spigot, MassiveCore and Factions version are you using?
Have you tried to run a local test server and test if it really is factions causing this? I would suggest checking your chat plugin, it will be most likely to cause this.

Also to your questions:
http://www.massivecraft.com/factions
Here is the user guide

**Comment by vasperal** [comment]
I fixed it thanks for the help saying it might be another plugin
