### ISSUE TITLE
F home does not teleport

### ISSUE THREAD

**Issue by KreWw** [MassiveCraft/Factions#820]
Hello guys. For some reason /f home does not teleport normal players. It shows teleporting in 10s but never actually teleports. It does work after I restart the server but once the server has been running for a day or longer it stops. And for some odd reason people that have all permissions(owner,admin) are teleported but they have insta-tp so the message does not even show up. Thank you.

**Comment by magnusulf** [comment]
The insta tp for admins is  intended (I can't remember the exact permission).
Fir the other that sounds weird, we will need more info
CraftBukkit version?
Factions version?
MassiveCore version?
Any error logs?
Factions and MassiveCore configuration.
And please don't say "latest" for the versions.

**Comment by 2spoopy4meh** [comment]
I have the same problem, and I closed my issue because I saw this one. I get no errors on Spigot 1.8 Build 27 in the console or the log files. Latest Factions and latest Massivecore on the bukkit files list (2.7.5 and 2.7.5). Factions mconf: http://pastebin.com/dbcs3tVZ Massivecore_mconf: http://pastebin.com/rv7wykeX Tests can be done on mc.ptcruisercraft.com in the factions section of the server. No faction permissions are restricted or given to players. They have all the default faction commands. Hope my information helps a bit :)

**Comment by 2spoopy4meh** [comment]
The issue got resolved when access to no tp delay was given to players, but when access was restricted again, the error returned. I really hope someone has an answer to this problem...

**Comment by magnusulf** [comment]
The TP system was overhauled some time ago. Does this issue persist?

**Comment by ulumulu1510** [comment]
No answer has been given by OP since three month now, I will deem this issue as resolved.
