### ISSUE TITLE
A Matter Of Utmost Importance

### ISSUE THREAD

**Issue by iTrollHard** [MassiveCraft/Factions#826]
Hello the herochat/factions integration does not work properly any more with recent version of factions. the factions and allies chat channels act as global channels. every player can see every faction and allies message regardless of what faction they are in.

i'm very good at configuring both and never had problems with it before upgrading from a much older factions version to the recent. i even uninstalled herochat and reinstalled. the faction and allies channels auto generated but they still did not work properly.

**Comment by iTrollHard** [comment]
and for the record, this is not a troll.

**Comment by iTrollHard** [comment]
i did some looking into it. every factions version after factions 1.8.2 the herochat integration is broken.

so pretty much every factions that relies on mstore. the newer versions are a lot better, but until it's fixed i have to use the old version...

**Comment by iTrollHard** [comment]
never mind it works. the method is just somewhat tricky.

please elaborate in the config explanations for future faction versions. there are many parts of the config not explained properly.

**Comment by iTrollHard** [comment]
i found out what the problem is. it's not that it works. the integration is still not perfect.

the problem is that the herochat factions config in the factions mconf is supposed to take priority over herochat, but when herochat is reloaded, herochat steals the priority from it. it's supposed to work properly no matter where the priority goes.

**Comment by ulumulu1510** [comment]
Reloading a plugin is never a good idea, because it can cause problems like this. One plugin takes priority over another, because they are/were both loaded and it simply confuses some of the systems.

Surely I agree about the problem though. Please provide us your MassiveCore, Factions, bukkit/spigot versions and a copy of your MConf (preferably a pastebin link). Additionally, if any errors occur, please also pastebin your console log for us.
