### ISSUE TITLE
disappearing factions and members

### ISSUE THREAD

**Issue by gravestristen** [MassiveCraft/Factions#871]
For some reason factions have been removed or people belonging to factions has been removed from the list and we cannot find out what is causing this.

**Comment by gh0ztbuster** [comment]
Factions removes players from factions when they have been offline for a specified period of time. You can edit the offline kick time or disable it in the mstore factions configuration.

**Comment by gh0ztbuster** [comment]
The faction_mconf options:
```
"removePlayerWhenBanned": true,
  "removePlayerMillisDefault": 864000000,
```
You must set the "removePlayerMillisDefault" to -1, setting it to 0 will result in wierd/random player removals.

**Comment by gravestristen** [comment]
it removes players after a day and an entire faction too?

**Comment by gh0ztbuster** [comment]
If your settings look like this, then yes. It does weird things.
```
 "removePlayerMillisDefault": 0,
```

**Comment by gh0ztbuster** [comment]
If you never want players to be kicked for inactivity, do this:
```
  "removePlayerMillisDefault": -1,
```

**Comment by gravestristen** [comment]
yes but entire factions are removed overnight.

**Comment by gh0ztbuster** [comment]
Factions runs clean ups at scheduled intervals.

I need to see the factions_mconf you had when factions were removed.

**Comment by ulumulu1510** [comment]
Best would be if you deliver your mconf and state your massivecore and factions version. Other wise helpig could get really hard. And also, does any error show on the log when a faction disappears?

**Comment by gravestristen** [comment]
http://www.mediafire.com/download/58mssoyqwzlqocc/mstore.zip

Theres the files for you.

**Comment by gh0ztbuster** [comment]
Result: Cannot find any configuration errors. Your issue either resides in saving/plugin errors or from players being offline for a long time. Be sure you are running the latest version of factions.

Settings: 
In your configuration, players are kicked after 10 days of inactivity (864000000 milliseconds). The older your faction becomes, the longer the inactivity kick for individual players becomes; you can check the inactivity kick time for a specific player with /f p <name>.

Mongodb (advanced users):
If you are using or intend to switch over to mongodb in future, remember data loss can occur due to saving conflictions in that database (I assume you currently use the default saving method: flatfile json stored in your mstore server directory).

**Comment by gravestristen** [comment]
we use the default file saving. perhaps you could come over to the server and help us?

**Comment by gh0ztbuster** [comment]
There isn't much more I could do being there than helping you on here.

Are you running MassiveCore and Factions 2.7.5?

Does the erasing persist?

**Comment by gravestristen** [comment]
whats your ign so i can whitelist you?
shipraidsmc.dtdns.net

**Comment by gh0ztbuster** [comment]
I sorry but I cannot join your server. You should post your version information and wait for further assistance from the mods creator. I thought your issue was simply a replica of a configuration issue I had a few months prior. I'm sorry but there isn't much more I can do since the issue is likely not related to configuration.

Note: There is no way to retrieve lost data once it is lost.

**Comment by magnusulf** [comment]
Could you tell us how to replicate this bug?

**Comment by ulumulu1510** [comment]
OP hasn't given an answer since the question 3 months ago. Without his help, I deem this Bug as resolved.
