### ISSUE TITLE
TPs Issues

### ISSUE THREAD

**Issue by XenRevo** [MassiveCraft/Factions#886]
I seem to be having some TPS issues. Here's what the timings are saying regarding the problem
![image](https://i.revo.pw/2488v01_24838H.png)

Do you know what could cause this?

**Comment by ulumulu1510** [comment]
This timing probably happens when you ban a player and he thus get kicked from the server. Under these circumstances, the play gets removed from the database and that takes some time as you may assume :) There ia no way we can make it faster without changing something on the backend....or you could use a more efficient backend System.

**Comment by XenRevo** [comment]
We hadn't banned anyone during those timings.

**Comment by oloflarsson** [comment]
This might have something to do with a slow economy plugin or the the server user cache being to small. If you use spigot increase the size of the user cache in spigot.yml.

**Comment by XenRevo** [comment]
Thanks, I will try this and get back to you.
