### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by Kedarin** [MassiveCraft/Factions#887]
Hello,
Since suffered a heavy attack on the server I have these errors spam my console (and the lag between server malgrès GST 18-20)

Log error : http://pastebin.com/KLvDVjJs

Thank you

**Comment by Kedarin** [comment]
Wow with a reboot it's ok .. ^^

**Comment by ulumulu1510** [comment]
These errors appear because the faction these players are in is not known to the system. Did you eventually manually delete some factions? 

But please describe more clearly when it happens, since when it happens, what versions of MassiveCore and Factions you use and everything that could help us pin point the issue.

**Comment by Kedarin** [comment]
This error just when the server restarts after a DDOS attack (I guess its endomage the system)
I Factions & MassiveCore 2.7.5

**Comment by Kedarin** [comment]
When I launch the server with Multicraft I have this error but when I launch with SSH not have error

**Comment by Kedarin** [comment]
Okey Multicraft don't have the right now it's ok
