### ISSUE TITLE
Players not recieving Player Age Bonus.

### ISSUE THREAD

**Issue by MithrandirCraft** [MassiveCraft/Factions#893]
Spigot MC version: 1.8.7
Factions version: 2.7.5
Mcore version: 2.7.5

Relevant configuration details:
 
 "removePlayerMillisPlayerAgeToBonus": {
    "1209600000": 864000000
  },

Explination:

All players are not recieving 10 extra faction permanence days for being 14 days inside a faction, when using the previously stated configuration. As can be seen by using the /f p <player> command on one of these sufficiently old members on a faction.

Some players on my server have remained inside their factions for months without leaving a single time, and they still don't get the +10 inactivity days bonus.

Please ask if I can provide any more information.

**Comment by magnusulf** [comment]
If I am not mistaken, the player age bonus is how long the player has been playing on the server.

**Comment by MithrandirCraft** [comment]
Woah, this is another very old ticket I don't remember very well. However, I know this issue could still exist, but I have the sensation it may have been fixed already.

I will check on this.

**Comment by magnusulf** [comment]
So it is no longer an issue?

**Comment by MithrandirCraft** [comment]
@magnusulf To be honest, I'd bet it provably still is an issue, if you are asking about it now.

I will check on this asap. I'm in the middle of exams right now :)

**Comment by ulumulu1510** [comment]
@MithrandirCraft, you haven't replied to this issue since then. IS this still an issue afterall?

**Comment by MithrandirCraft** [comment]
@ulumulu1510 oh, I forgot about this. Thanks for remembering it. However, it's a very old issue, and re-checking this now may be a bit tricky.

I'm gonna take a look at it now.

**Comment by MithrandirCraft** [comment]
Hmh... looks like it's working properly now. What do you think?:
![screenshot_1](https://cloud.githubusercontent.com/assets/6623704/13359501/e51fbc20-dcb4-11e5-8480-33fa1678ff8b.png)

**Comment by MithrandirCraft** [comment]
btw, quick question offtopic (I hope you don't mind): Could I get some info on how to translate as much of faction's messages as possible, to my own language?

**Comment by ulumulu1510** [comment]
There is no proper and fast solution to this. If someone were to make a PR for a language file, that would be the best solution of course. I could even help you with that. Because you have to fork the project or download it anyways.

In the long run, forking is much better, because you can apply our changes to your language branch. If you don't know how to fork a project, tranlating factions will be a real pain, so I suggest you google yourself through that.

If you have learned (or already know) how to fork a project, please make one class where you have only public static Strings with all the messages and redirect all the messages there. From there on, we could work on a translation solution once and for all together.


Disclaimer: If you have no knowledge on Java what so ever and don't know how to work with it, translating this plugin is not going to work out for you.

**Comment by MithrandirCraft** [comment]
I might do this eventually. But when the time comes, I'll be opening a ticket for it.

**Comment by ulumulu1510** [comment]
You would make a lot of people happy if you would :)
