### ISSUE TITLE
Allowing pvp for neutral factions

### ISSUE THREAD

**Issue by TheExceed** [MassiveCraft/Factions#902]
I cannot seem to find where to allow a player to attack someone of a neutral faction inside their claim.
Any help would be great.

**Comment by magnusulf** [comment]
Could you elaborate?
As far as I am concerned you can always attack neutral people and enemies inside your own land.

**Comment by TheExceed** [comment]
It seems when someone who's faction is neutral to yours is in their claimed territory, you cannot attack them.

**Comment by TheExceed** [comment]
But glad it toom 5 months to respond...

**Comment by magnusulf** [comment]
That is the intended behaviour. So you have to enemy people before you can kill them in their own home. As it seems there is no config option for that. The solution is simply to enemy people.

Also don't spite, especially when you asked a poorly phrased question.

**Comment by TheExceed** [comment]
Why not add the option then? It seemed quite clear to me.
Are you sure you're competent enough to be a collaborator?

**Comment by magnusulf** [comment]
Why not add the option you ask, because it takes time and I currently have a list of more than 10 bugs which needs to be fixed and 5 different features I'd like to implement.

It seemed quite clear to you. Yes of course the meaning of a written text is clear to the author. But sometimes a sentence can be ambiguous, and thus be interpreted different by a reader. In your case the pronoun "their" could be either of the mentioned persons, and that lead to confusion. I interpreted as one of the persons and you mean the other. Being clear and avoiding ambiguity, even if it requires a few more words, can be the key to expressing something specific.

Yes I am pretty sure I am competent enough to be a collaborator.
