### ISSUE TITLE
Error coming from time to time

### ISSUE THREAD

**Issue by killertudse** [MassiveCraft/Factions#906]
Hello.

I have this error which pops up my console quite frequently.

http://pastebin.com/NYwBvDb4

I am using spigot, and the latest version of factions.

**Comment by ulumulu1510** [comment]
So I guess you are using Spigot 1.8.7 and
Factions/MassiveCore 2.8 when you say latest.

What version of Java are you running this with? Because the error is pointing at a missing method in the java library. If you want this error to disapear you will have to update your java version to 1.8.

@Cayorion
This is a valid Error in our Code, if we want to stay java 1.7/1.6 complient. The Method Double.isFinite (double d) is existing since Java 8, thus all running with 1.7 or below will get this error. https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#isFinite-double-
Caused by:
https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/util/MUtil.java#L629

Im the setDamage and scaleDamage methods they are used quite frequently.

**Comment by ulumulu1510** [comment]
@killertudse 
This problem is being worked on and will probably be solved in the next release :).
Thank you very much for reporting it.

**Comment by oloflarsson** [comment]
Update to Java 8 for now. The next release will have this fixed.
