### ISSUE TITLE
Factions API With Maven Shading.

### ISSUE THREAD

**Issue by dznSpencer** [MassiveCraft/Factions#922]
Using Factions & MCore in Java Build Path & shadng them with Maven. Getting this error.

error: package com.massivecraft.factions.entity does not exist

Also recommend getting a Maven build server. Would help a ton for developers.

**Comment by MarkehMe** [comment]
What version of Factions and what version of MassiveCore? 

Why are you trying to shade them together, whats wrong with having them side by side - they plugins will load faster. Can you throw your build file on Pastebin? I'll try help you compile it.  

Maven is a bit of a mess of a build system (and slow) - if one was to be implemented I'd suggest using Gradle, or even better Facebook created Buck Build (https://buckbuild.com/) which is really fast!

**Comment by NoChanceSD** [comment]
+1 for this. Please add a maven repository, it would make it a lot easier to depend on.

**Comment by MarkehMe** [comment]
You can add the Factions and MassiveCore jar into your local maven repository.

Download MassiveCore and Factions into the ```libs/``` folder of your project 
* http://dev.bukkit.org/bukkit-plugins/mcore/files/44-massive-core-2-8-0/
* http://dev.bukkit.org/bukkit-plugins/factions/files/76-factions-2-8-0/

From inside your project directory, install each dependency: 

__MassiveCore__:
```
 mvn install:install-file
-Dfile=libs/MassiveCore.jar
-DgroupId=MassiveCraft
-DartifactId=MassiveCore
-Dversion=2.8.0
-Dpackaging=jar
-DgeneratePom=true
```

__Factions__:
```
 mvn install:install-file
-Dfile=libs/Factions.jar
-DgroupId=MassiveCraft
-DartifactId=Factions
-Dversion=2.8.0
-Dpackaging=jar
-DgeneratePom=true
```

```generatePom``` will automatically update your pom file for you.

Consider using faster build tools like Gradle or Buck Build. 

If you want I can write a small tool to do this for you semi-automatically for all MassiveCraft plugins. 

Since the original issue of this issue ticket has been solved I'm going to close it for now. I'm not sure if a Maven repo will be added, but using a local maven repo is your best choice for now.
