### ISSUE TITLE
Q: Factions Members Offline AND Faction Plots

### ISSUE THREAD

**Issue by Echo4211** [MassiveCraft/Factions#948]
Hey there

I got a question, a few year or two ago I used to have Factions on my server, and I remember that the plugin had a function were you enable the enemies to be able to go into players chest from another faction when they were online, but the moment they went offline, it gave the raiders a 5 minute timer before being locked out completely. How do I enable this with the latest factions, cause I dont seem to find anything close to it.

Also I remember a faction version were you were capable of giving certain chunks to certain members, giving only them permission to build/open/etc, how do I enable this with the latest version?

Also were did the faction chat went too? 

Its sad to see that all these good things are missing ;(

**Comment by ulumulu1510** [comment]
Hello @Echo4211 ,
The raiding option ( I don't even remember this one, it must be really old) has completly fallen of the radar and nothing like it has been implemented in the newer versions. The only thing you can do is find another plugin which hooks into factions that does this for you.

Distributing build rights in faction is done over the comand /f access. With it, you can grant certain players or factions build rights to your faction, even when your flags don't all it for that relation. Mess around with it and I assure you, you will get the functionality just as you want.

FactionChat is gone since wuite a lot of time. The reason therefor is, that a plguni should only do one thing at a time. It sill leaves you with some basic chat-*integration*, which can be turned on and off in the mconf of factions. This is not inheritly bad, because many chat plugins offer the chat functionality faction once offered and much more. They focused on chat, we focused on factions. Simple as that.

If you have any other questions, you can make another ticket or ask another question to my answer in this ticket.

**Comment by Echo4211** [comment]
So basically, if I allow people to raid by adding 'ENEMY' into the permissions for Containers, Doors, and such, they can go into everyones bases 24/7 no matter if they are online or offline?

**Comment by ulumulu1510** [comment]
Yes, that is the case. But if you chose to do so, be aware that some flags can (in the standart case) be edited by the faction members. If you want to disable that, make sure you set "editable" to false in your mstore/factions/mperm/container.json file (if you use the standart database system).
