### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: java.lang.Double.isFinite(D)Z

### ISSUE THREAD

**Issue by luniso** [MassiveCraft/Factions#952]
This error happens constantly in my spigot 1.8.8 server, and i'm actually using factions 2.8.0. Here's the error report:
http://pastebin.com/qKm77XbC
I dont' use the 2.8.1 because it works even worse, when i type /f list it makes and error too, so please if you could fix it it would be awesome.
Thank You, Luis.

**Comment by ulumulu1510** [comment]
This is why we only support the newest versions:

This exact bug was fixed in MassiveCore 2.8.1, which is already out for quite some time. Please download and put the newest version of MassiveCore and Factions onto your server.

If you have further issues (like the one you mentioned) please post them in a separate issue.
