### ISSUE TITLE
Factions 1.6.9.5

### ISSUE THREAD

**Issue by Gardiac** [MassiveCraft/Factions#957]
Hi Im using Factions 1.6.9.5 and im asking how do I add prefix to factions like: &6[<faction name>] [Group] <user name>: <message>

**Comment by ulumulu1510** [comment]
I am sorry, but we do not maintain old software of ours and I for one do not posess the knowledge anymore how our configuration files looked in that specific version.
Have you considered updating to 2.8.2? (you will have to update slowly, version by version to make sure no harm is done to your databases). But it is surely worth the effort. Factions has gotten more safe and has squashed a lot of bugs since then. And there has been additional features and usability improvements.

**Comment by Gardiac** [comment]
I dont want to update , well exactly I already did before but new style of Factions is not like I want.. and new look of /f who and some other stuff..

**Comment by MarkehMe** [comment]
A lot has changed over the years, if you're unhappy with command structure there are alternatives plugins to fix this (Such as FactionsAlias) http://dev.bukkit.org/bukkit-plugins/factionsalias/

However, Factions v2 is __a lot__ more powerful than Factions v1 in both terms of functionality and performance.
