### ISSUE TITLE
Error: when trying to use /f money commands.

### ISSUE THREAD

**Issue by madtomic** [MassiveCraft/Factions#963]
http://pastebin.com/CiR5Tkj6

**Comment by ulumulu1510** [comment]
Your plugin Iconomy cannot handle the lenght our faction UUID. This is rather strange, since a players UUID has the same length (same format= same length). 

If your Economyplugin cannot handle UUIDs, it is not fit for this era. Saving any data on playernames is inheritly unsafe, since they can be changed now.

In conclussion, the fault lies in your economy plugin.

**Comment by madtomic** [comment]
Thank you for explaining.
