### ISSUE TITLE
I need help With The Config!

### ISSUE THREAD

**Issue by Junhaochia** [MassiveCraft/Factions#982]
I dont understand why

{
  "aliasesF": [
    "f",
    "factions"
  ],
  "worldsClaimingEnabled": {
    "standard": false,
    "exceptions": [
    "Faction",
    "Faction_End",
    "Faction_Nether"
  ]
  },
  "worldsPowerLossEnabled": {
    "standard": false,
    "exceptions": [
    "Faction",
    "Faction_End",
    "Faction_Nether"
  ]
  },
  "worldsPvpRulesEnabled": {
    "standard": false,
    "exceptions": [
    "Faction",
    "Faction_End",
    "Faction_Nether"
  ]
  },

^Wont Work^
When i Do /f or /faction it says  Unknown command. Type "/help" for Help

1) This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
2) MassiveCore Version: 2.8.2
3) MassiveCore's Factions Version: 2.8.2

**Comment by Junhaochia** [comment]
I just wanted Alias to be /f and /faction
And i want it to enabled in this 3 worlds: Faction , Faction_End , Faction_Nether

**Comment by ulumulu1510** [comment]
Please state the following:
* Spigot version
* MassiveCore version
* Factions version

If you provide that, we can help you further.

**Comment by Junhaochia** [comment]
1) This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
2) MassiveCore Version: 2.8.2
3) MassiveCore's Factions Version: 2.8.2

**Comment by ulumulu1510** [comment]
Make sure that the worlds are written with correct casing at first (it might be "faction" instead of "Faction" or "faction_end" instead of "Faction_End"). From my experience, most worlds are all lowercase, but better make sure. You can try different casing at runtime, if you are unsure.

Are you sure that the plugin is loaded and functional? If you watch your log, there should be a bright yellow entry that states so.
Try "/massivecore" aswell. If that doesn't work, your plugins are not initialized somehow.

Otherwise your json seems to be fine. If the json is wrong, the server will tell you.

Asside, I recommend running the spigot jar instead of the craftbukkit one. We sometimes use its features for 1.8+ versions.

If this all doesn't help, please provide some more information:
* Is it a clean install or are there other plugins?
* Have you tried this with a clean-install?
* Are there any errors showing up on the logs, maybe on startup?

**Comment by Junhaochia** [comment]
@ulumulu1510 I am using Spigot

**Comment by ulumulu1510** [comment]
@Junhaochia Misinterpreted your last answer then. What about the other questions?

**Comment by Junhaochia** [comment]
Well Its Doesnt work with the Config i made

**Comment by Junhaochia** [comment]
opps wrong button i meant to press coment 

The Config above i made doesnt work.

**Comment by magnusulf** [comment]
Have you tried a clean install with only MassiveCore and Factions?

**Comment by MarkehMe** [comment]
Can you also try pasting your config into http://jsonlint.com/ to ensure it is valid?

**Comment by Junhaochia** [comment]
let me see

**Comment by Junhaochia** [comment]
Valid JSON

**Comment by Junhaochia** [comment]
wait now its works

**Comment by Junhaochia** [comment]
Werid
