### ISSUE TITLE
CommandSender Link Failed (Cauldron) - Issue Identified

### ISSUE THREAD

**Issue by DraksterAU** [MassiveCraft/Factions#986]
Hi All,

I built a custom version of v2.8.2 Mcore/Factions excluding the commits below, as they line up with the 2.7.4 Cauldron lack of support and have found that things work perfectly fine without  them!

Can a Dev please take a look at this one - Cauldron/Kcauldron support may simply be an IF statement excluding this change?

Please excuse my ignorance as far as coding goes, but I have thoroughly tested the custom build with no issues...

https://github.com/MassiveCraft/Factions/commit/6ab443c8b769e58196f07e101e7560093251fa43

and this one 

https://github.com/MassiveCraft/MassiveCore/commit/c1db14eebef7dff790f6c6364184796a243e126a

**Comment by ulumulu1510** [comment]
Your effort is remarkable, but note this:
We cannot simply revert a commit we made 1.5 Years ago, we should rather investigate the issue further. As you seem to have reasonable skills in testing and compiling plugins yourself, why don't you help us finding the reall issue here? Also, from us two, you are the one with a functioning cauldron server.

I have made a little investigation on my end and I can tell you what code you will have to investigate (roughly 70 lines) and put debug code in which you can then foreward to us so we can see how cauldron behaves differently from the normal bukkit/spigot implementation.

https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/engine/EngineMassiveCoreDatabase.java#L57

Line 57 till 135 are the ones that set the CommandSender in our SenderEntityColls. This is where we reference the CommandSender to the players UUID alongside a few other things.

Whats improtant in there:
There are several listeners which link a players CommandSender with his UUID. There is exactly one cause which leads to the Commandsender being Null (which causes the issue):
https://github.com/MassiveCraft/MassiveCore/blob/master/src/com/massivecraft/massivecore/engine/EngineMassiveCoreDatabase.java#L86

When the player goes offline (or appears to be), his reference is set to null. Thats because banned players (who fail to log in properly) should get the senderLink unset.

This is what you will have to investigate: 
* Put debug code in all ligon listeneers and the methods between lines 57 and 135.
* Check the CommandSender reference. When does it happen to be null?
* It could be the online method of bukkit, pelase debug that aswell. Maybe Cauldron has modified that behaviour somehow or has screwed up on it.

I neither have the time nor Cauldron server to investigate this, so please help us on this cause.

**Comment by DraksterAU** [comment]
I think you have my misunderstood, I don't know how to do any of that.
